# Generated by Django 5.2.14 on 2026-06-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_employe_image_produit_image_produit_prix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'managed': True, 'ordering': ('-date',), 'permissions': [('view_cuisine', "Peut voir l'écran cuisine"), ('change_statut_cuisine', 'Peut changer le statut des commandes en cuisine')]},
        ),
        migrations.AddField(
            model_name='commande',
            name='statut_cuisine',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Prête', 'Prête')], db_column='Statut_Cuisine', default='En attente', max_length=20, null=True),
        ),
    ]
