# Generated by Django 5.2.14 on 2026-06-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(db_column='id_Client', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=20, null=True)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=20, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=45, null=True)),
                ('type_de_client', models.CharField(blank=True, db_column='Type_de_Client', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Client',
                'ordering': ('nom', 'prenom'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.IntegerField(db_column='id_Employe', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=20, null=True)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=20, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=15, null=True)),
                ('salaire', models.IntegerField(blank=True, db_column='Salaire', null=True)),
                ('date_embauche', models.DateField(blank=True, db_column='Date_Embauche', null=True)),
            ],
            options={
                'db_table': 'Employe',
                'ordering': ('nom', 'prenom'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.IntegerField(db_column='id_Equipement', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=45, null=True)),
                ('etat', models.CharField(blank=True, db_column='Etat', max_length=45, null=True)),
                ('date_achat', models.DateField(blank=True, db_column='Date_Achat', null=True)),
            ],
            options={
                'db_table': 'Equipement',
                'ordering': ('nom',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.IntegerField(db_column='id_Facture', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('montant', models.IntegerField(blank=True, db_column='Montant', null=True)),
                ('type_facture', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Facture',
                'ordering': ('-date', '-id_facture'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.IntegerField(db_column='id_Fournisseur', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=45, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=15, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Fournisseur',
                'ordering': ('nom',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id_ingredient', models.IntegerField(db_column='id_Ingredient', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=45, null=True)),
                ('unite_de_mesure', models.CharField(blank=True, db_column='Unite_de_Mesure', max_length=45, null=True)),
                ('type_ingredient', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Ingredient',
                'ordering': ('nom',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id_poste', models.IntegerField(db_column='id_Poste', primary_key=True, serialize=False)),
                ('libelle_poste', models.CharField(blank=True, db_column='Libelle_Poste', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Poste',
                'ordering': ('libelle_poste',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id_table', models.IntegerField(db_column='id_Table', primary_key=True, serialize=False)),
                ('numero_table', models.CharField(blank=True, db_column='Numero_Table', max_length=3, null=True)),
                ('capacite', models.IntegerField(blank=True, db_column='Capacite', null=True)),
                ('commentaire', models.TextField(blank=True, db_column='Commentaire', null=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'Table',
                'ordering': ('numero_table',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.IntegerField(db_column='id_Vehicule', primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(blank=True, db_column='Immatriculation', max_length=15, null=True)),
                ('modele', models.CharField(blank=True, db_column='Modele', max_length=20, null=True)),
                ('marque', models.CharField(blank=True, db_column='Marque', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Vehicule',
                'ordering': ('immatriculation',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.IntegerField(db_column='id_Commande', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('type_commande', models.CharField(blank=True, db_column='Type', max_length=30, null=True)),
                ('montant_total', models.IntegerField(blank=True, db_column='Montant_Total', null=True)),
                ('mode_de_paiement', models.CharField(blank=True, db_column='Mode_de_Paiement', max_length=45, null=True)),
                ('client', models.ForeignKey(blank=True, db_column='id_Client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='restaurant.client')),
            ],
            options={
                'db_table': 'Commande',
                'ordering': ('-date',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deplacement',
            fields=[
                ('id_deplacement', models.IntegerField(db_column='id_Deplacement', primary_key=True, serialize=False)),
                ('date_depart', models.DateTimeField(blank=True, db_column='Date_depart', null=True)),
                ('destination', models.TextField(blank=True, db_column='Destination', null=True)),
                ('distance_totale', models.DecimalField(blank=True, db_column='Distance_totale', decimal_places=2, max_digits=10, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, db_column='id_Chauffeur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deplacements', to='restaurant.employe')),
                ('vehicule', models.ForeignKey(blank=True, db_column='id_Vehicule', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deplacements', to='restaurant.vehicule')),
            ],
            options={
                'db_table': 'Deplacement',
                'ordering': ('-date_depart',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActionMarketing',
            fields=[
                ('id_action', models.IntegerField(db_column='id_Action', primary_key=True, serialize=False)),
                ('type_action', models.CharField(blank=True, db_column='Type_Action', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('date_debut', models.DateField(blank=True, db_column='Date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='Date_fin', null=True)),
                ('budget', models.IntegerField(blank=True, db_column='Budget', null=True)),
                ('responsable', models.ForeignKey(blank=True, db_column='id_Responsable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions_marketing', to='restaurant.employe')),
            ],
            options={
                'db_table': 'Action_Marketing',
                'ordering': ('-date_debut',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ingredient', models.OneToOneField(db_column='id_Ingredient', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stock', serialize=False, to='restaurant.ingredient')),
                ('quantite_actuelle', models.DecimalField(blank=True, db_column='Quantite_Actuelle', decimal_places=2, max_digits=10, null=True)),
                ('seuil_alerte', models.DecimalField(blank=True, db_column='Seuil_Alerte', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Stock',
                'ordering': ('ingredient__nom',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id_approvisionnement', models.IntegerField(db_column='id_Approvisionnement', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('quantite', models.DecimalField(blank=True, db_column='Quantite', decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.IntegerField(blank=True, db_column='Prix_Unitaire', null=True)),
                ('deplacement', models.ForeignKey(blank=True, db_column='id_Deplacement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnements', to='restaurant.deplacement')),
                ('fournisseur', models.ForeignKey(blank=True, db_column='id_Fournisseur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnements', to='restaurant.fournisseur')),
                ('ingredient', models.ForeignKey(blank=True, db_column='id_Ingredient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvisionnements', to='restaurant.ingredient')),
            ],
            options={
                'db_table': 'Approvisionnement',
                'ordering': ('-date',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id_livraison', models.IntegerField(db_column='id_Livraison', primary_key=True, serialize=False)),
                ('commande', models.OneToOneField(blank=True, db_column='id_Commande', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraison', to='restaurant.commande')),
                ('deplacement', models.ForeignKey(blank=True, db_column='id_Deplacement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to='restaurant.deplacement')),
            ],
            options={
                'db_table': 'Livraison',
                'ordering': ('id_livraison',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id_maintenance', models.IntegerField(db_column='id_Maintenance', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('type_maintenance', models.CharField(blank=True, db_column='Type', max_length=45, null=True)),
                ('commentaire', models.TextField(blank=True, db_column='Commentaire', null=True)),
                ('equipement', models.ForeignKey(blank=True, db_column='id_Equipement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='restaurant.equipement')),
                ('technicien', models.ForeignKey(blank=True, db_column='id_Technicien', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenances', to='restaurant.employe')),
            ],
            options={
                'db_table': 'Maintenance',
                'ordering': ('-date',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('pk', models.CompositePrimaryKey('employe_id', 'poste_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, db_column='Date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='Date_fin', null=True)),
                ('employe', models.ForeignKey(db_column='id_Employe', on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='restaurant.employe')),
                ('poste', models.ForeignKey(db_column='id_Poste', on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='restaurant.poste')),
            ],
            options={
                'db_table': 'Affectation',
                'ordering': ('-date_debut',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.IntegerField(db_column='id_Produit', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=30, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=45, null=True)),
                ('duree_cuisson', models.CharField(blank=True, db_column='Duree_Cuisson', max_length=20, null=True)),
                ('nombre_personnes', models.IntegerField(blank=True, db_column='Nombre_Personnes', null=True)),
                ('createur', models.ForeignKey(blank=True, db_column='id_Createur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits_crees', to='restaurant.employe')),
            ],
            options={
                'db_table': 'Produit',
                'ordering': ('nom',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('pk', models.CompositePrimaryKey('commande_id', 'produit_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(blank=True, db_column='Quantite', decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.IntegerField(blank=True, db_column='Prix_Unitaire', null=True)),
                ('commande', models.ForeignKey(db_column='id_Commande', on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='restaurant.commande')),
                ('produit', models.ForeignKey(db_column='id_Produit', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='restaurant.produit')),
            ],
            options={
                'db_table': 'Ligne_Commande',
                'ordering': ('commande_id', 'produit__nom'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompositionProduit',
            fields=[
                ('pk', models.CompositePrimaryKey('produit_id', 'ingredient_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantite_utilisee', models.DecimalField(blank=True, db_column='Quantite_Utilisee', decimal_places=2, max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(db_column='id_Ingredient', on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='restaurant.ingredient')),
                ('produit', models.ForeignKey(db_column='id_Produit', on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='restaurant.produit')),
            ],
            options={
                'db_table': 'Composition_Produit',
                'ordering': ('produit__nom', 'ingredient__nom'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.IntegerField(db_column='id_Reservation', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('heure', models.TimeField(blank=True, db_column='Heure', null=True)),
                ('statut', models.CharField(blank=True, db_column='Statut', max_length=45, null=True)),
                ('client', models.ForeignKey(blank=True, db_column='id_Client', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.client')),
                ('table', models.ForeignKey(blank=True, db_column='id_Table', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='restaurant.restauranttable')),
            ],
            options={
                'db_table': 'Reservation',
                'ordering': ('-date', '-heure'),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('pk', models.CompositePrimaryKey('superviseur_id', 'employe_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, db_column='Date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='Date_fin', null=True)),
                ('employe', models.ForeignKey(db_column='id_Employe', on_delete=django.db.models.deletion.PROTECT, related_name='supervisions_recues', to='restaurant.employe')),
                ('superviseur', models.ForeignKey(db_column='id_Superviseur', on_delete=django.db.models.deletion.PROTECT, related_name='supervisions_donnees', to='restaurant.employe')),
            ],
            options={
                'db_table': 'Supervision',
                'ordering': ('-date_debut',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VariationStock',
            fields=[
                ('id_variation', models.IntegerField(db_column='id_Variation', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('type_variation', models.CharField(blank=True, db_column='Type', max_length=10, null=True)),
                ('quantite', models.DecimalField(blank=True, db_column='Quantite', decimal_places=2, max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(blank=True, db_column='id_Ingredient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variations_stock', to='restaurant.ingredient')),
            ],
            options={
                'db_table': 'Variation_Stock',
                'ordering': ('-date', '-id_variation'),
                'managed': True,
            },
        ),
    ]
