# Generated by Django 5.2.14 on 2026-06-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employes/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(db_column='Prix', default=2500),
        ),
    ]
